edx_when/__init__.py, edx_when/api.py
openedx.features.course_experience.tests.views.test_course_home.TestCourseHomePageAccess.test_home_page_5
and
openedx.features.course_experience.tests.views.test_course_home.TestCourseHomePageAccess.test_home_page_6
failed for me as a result of this format string being insufficiently
permissive
JIRA:EDUCATOR-3765 as part of getting the switch deployed
Today please
instructions.
tests above
**Reviewers:**
finished.
**Author concerns:** List any …
=> Fixing test failures

edx_when/__init__.py, edx_when/api.py, edx_when/signals.py, tests/test_api.py
For [PROD-291](https://openedx.atlassian.net/browse/PROD-291).
Self-paced courses will not store due dates in edx-when. Only the course start and end dates will be in the database.
=> Handle self-paced courses by not saving due dates in the database.

edx_when/__init__.py, edx_when/api.py, edx_when/field_data.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, tests/test_api.py
Instead of managing a bunch of waffle flags, let's just look at whether there's data in the database. If so, edx-when is enabled for that course. If not, then the course needs to be republished.
=> Changed course enablement check to look at the database rather than a waffle flag

edx_when/__init__.py, edx_when/signals.py
For [CR-1089](https://openedx.atlassian.net/browse/CR-1089):
Students can't submit problems because courses which were instructor-paced and then switched to self-paced still have active due dates in edx-when's tables.
=> Remove course-level due dates from self-paced courses.

edx_when/__init__.py, edx_when/api.py, edx_when/models.py, tests/test_api.py
**Description:**
The existing code didn't correctly reset the returned date after an override was removed. This PR fixes that, and adds a test that verifies it.
**Reviewers:**
finished.
=> Correctly account for un-overriding UserDates

edx_when/__init__.py, edx_when/api.py, edx_when/field_data.py, edx_when/models.py, tests/test_api.py, tests/test_models.py, tests/test_models_app/migrations/0001_initial.py, tests/test_models_app/models.py, tests/test_xblock_services.py
CourseEnrollments don't have a `related_name` set, so they use the
`courseenrollment_set` access pattern for reverse lookups.
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Use the correct name for the enrollments model lookup

.annotation_safe_list.yml, edx_when/__init__.py, edx_when/api.py, edx_when/models.py, test_settings.py, tests/test_api.py, tests/test_xblock_services.py
With this change, the api will only return relative block dates and/or relative user override dates if a waffle flag is enabled for the given course and user.
Also, remove the unused and inaccurate api decorator override_enabled. It referenced an old waffle flag that gated all of edx-when. Due to this change, I've bumped the version to 1.0.0.
https://openedx.atlassian.net/browse/AA-27
=> Enable relative dates based off waffle

AUTHORS, edx_when/__init__.py, edx_when/api.py, edx_when/models.py, tests/test_api.py, tests/test_models.py
**Description:** 
This PR handles a case when a user doesn't have a schedule associated with his enrollment. This will make the code more robust by handing this edge case and return None. 
**JIRA:** 
[Reports of Extensions Button Not Working](https://openedx.atlassian.net/browse/CR-1883)
**Merge deadline:** As soon as possible.
instructions.
1. Go to **Extensions** tab on the instructor dashboard. 
2. Given that the schedule does not exist for a user for his course enrollment. Fill in the data for **Individual due to date extensions**  form and hit **Change due date...**
3. After the fix, this should pass and get a successful message. 
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant …
=> fix schedules for user view.

edx_when/__init__.py, edx_when/api.py, edx_when/models.py, tests/test_api.py
In the scenario where the date returned for a relative date
would be past the end date (such as an assignment due date),
we want to prefer the course end date instead.
=> AA-55: Updating relative date return logic

edx_when/__init__.py, edx_when/api.py, tests/test_api.py
Try to reduce the number of writes we do when setting dates, by just checking if the data has actually changed first.
=> Don't write to db if nothing changed

CHANGELOG.rst, edx_when/__init__.py, edx_when/api.py, tests/test_api.py
The get_dates_for_course function makes large queries to fetch
ContentDate objects. Since this function is called from almost
any courseware operation (we fetch a whole course worth of dates
at a time when doing XBlock operations), it started putting a
lot of stress on the database under load. In order to help
alleviate some of that pressure, this commit uses memcached to
cache this data.
Ideally, we would be smarter about only grabbing the data we
actually need, rather than grabbing the entire course's date
information at once. Also, the fact that we're just shoving
model objects into the cache means that this functionality relies
on using pickle caching serialization rather than JSON, which is
worse from a security and compatibility point of view. This is not
great code, it's just the …
=> Simple caching of ContentDate on a per course basis.

edx_when/__init__.py, edx_when/api.py, tests/test_api.py
List of generated queries being run.
For User IDs of learners with UserDate overrides (only used as subquery):
```
SELECT DISTINCT "edx_when_userdate"."user_id" 
FROM "edx_when_userdate" 
INNER JOIN "edx_when_contentdate" 
ON (
"edx_when_userdate"."content_date_id" = "edx_when_contentdate"."id"
) 
INNER JOIN "edx_when_datepolicy" 
ON (
"edx_when_contentdate"."policy_id" = "edx_when_datepolicy"."id"
) 
WHERE (("edx_when_userdate"."abs_date" IS NULL 
AND django_datetime_cast_date((django_format_dtdelta('+', "edx_when_datepolicy"."abs_date", "edx_when_userdate"."rel_date")), NULL) = 2019-03-22
) 
OR (
django_datetime_cast_date("edx_when_datepolicy"."abs_date", NULL) = 2019-03-22 AND "edx_when_userdate"."rel_date" IS NULL))
```
For Schedules of learners with UserDate overrides:
```
SELECT …
```
=> AA-68: Adds function to find users with assignments due on a day

CHANGELOG.rst, edx_when/__init__.py, edx_when/api.py, edx_when/models.py, tests/test_api.py, tests/test_models.py, tests/test_models_app/migrations/0001_initial.py, tests/test_models_app/models.py
The cutoff date is the point past which the learner will not have time to complete the course, because expected due dates would be due past the course end date.
This new check only considers if the learner's original schedule was past the cutoff, it does not consider schedules that have been reset. (i.e. we still allow for learners that reset their schedule close to the course end date, by clustering their due dates at course end).
Related to https://github.com/edx/frontend-app-learning/pull/100
=> AA-195: Don't give rel dates past cutoff date

CHANGELOG.rst, README.rst, edx_when/__init__.py
Updated the README file.
Travis badge is now pointing to 'travis-ci.com' instead of 'travis-ci.org'
JIRA: https://openedx.atlassian.net/browse/BOM-2089
=> Updated the travis badge to point to travis-ci.com

CHANGELOG.rst, edx_when/__init__.py, edx_when/api.py, edx_when/models.py, tests/test_models.py
It happens for legitimate reasons like staff users viewing a course they are not enrolled in.
If edx-platform cares about it, they can check on their side (and thus just log once instead of many times).
=> Don't warn if we're missing a schedule for relative dates

tox.ini
This is required for newer pylint-django versions.
=> fix: set DJANGO_SETTINGS_MODULE for quality test

.github/workflows/upgrade-python-requirements.yml
Repository is no longer owned by engage, so notifications should be rerouted to cosmonauts.
=> fix: transfer from engage to cosmonauts

.github/workflows/ci.yml, CHANGELOG.rst, edx_when/__init__.py, edx_when/urls.py, setup.py, tests/test_api.py, tox.ini
**Description:**
- Add support for  Django 4.2
- Bump the version
**Codemod used to upgrade this repo:**  https://github.com/adamchainz/django-upgrade
**Ticket:** https://github.com/edx/upgrades/issues/163
=> fix: update for django 4.2, update changelog.

CHANGELOG.rst, edx_when/__init__.py, edx_when/api.py, edx_when/utils.py, tests/test_api.py
Calls to render a Unit were calling this function many times, even when
schedules are not enabled. This was leading to noticeable performance
issues in production, particularly for Units with many components.
I still need to test this properly, which is probably going to involve
hacky looking mocking because of the weird model relationship this has
with edx-platform (where it's actually importing the Schedule model
from edx-platform).
=> perf: request cache get_schedule_for_user

.github/workflows/ci.yml, CHANGELOG.rst, edx_when/__init__.py, pylintrc, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt, tox.ini
Resolves #271 
- Updated Python version in tox
- Bumped actions/checkout to v4
- Bumped actions/setup-python to v5
- Fixed Pylint issues
- Updated Requirements and changelog
=> chore: Dropped support for Python 3.8 and added support for Python 3.12
