openedx/edx-when

edx_when/api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Prevent anonymous users from messing with queries

edx_when/field_data.py, tests/test_xblock_services.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Prevent AttributeError for missing block from crashing everything

edx_when/api.py, edx_when/apps.py, edx_when/signals.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Convert string dates to datetime

edx_when/__init__.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> bump version

edx_when/__init__.py, edx_when/api.py, tests/test_api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Add api for getting date from block

openedx.yaml, tests/test_api.py
I like this new approach to [code ownership](https://youtu.be/rghDqZYTvvc).
=> I own this

edx_when/__init__.py, edx_when/field_data.py, tests/test_xblock_services.py
This is required for edx/edx-platform#21318 to work correctly.
=> Changed FieldData inheritance to match other FieldData subclasses' behavior

edx_when/__init__.py, edx_when/field_data.py
**Description:** Update field_data log level to DEBUG to reduce log volume
**JIRA:** N/A
**Dependencies:** N/A. 
**Merge deadline:** 
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Update field_data log level from INFO to DEBUG

edx_when/__init__.py, edx_when/api.py, edx_when/models.py, tests/test_api.py, tests/test_models.py, tests/test_xblock_services.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Add a test that demonstrates how bad the query performance can be

edx_when/__init__.py, edx_when/field_data.py, requirements/base.in, requirements/base.txt, requirements/dev.in, requirements/dev.txt, requirements/doc.in, requirements/doc.txt, requirements/pip-tools.in, requirements/pip-tools.txt, requirements/quality.in, requirements/quality.txt, requirements/test.in, requirements/test.txt, requirements/travis.in, requirements/travis.txt, setup.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Use the read-replica for loading dates into the DateLookupFieldData

edx_when/__init__.py, edx_when/api.py, edx_when/field_data.py, requirements/constraints.txt, tests/test_models.py, tests/test_xblock_services.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Fix quality issues that blocked master

edx_when/api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Limit the fields queried when fetching all dates for a course

edx_when/__init__.py, edx_when/api.py, tests/test_api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Handle race-condition-created duplicate DatePolicy objects

edx_when/__init__.py, edx_when/admin.py, edx_when/apps.py, edx_when/models.py
https://openedx.atlassian.net/browse/AA-93
=> Add admin panels for all models

.travis.yml, CHANGELOG.rst, edx_when/__init__.py, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, tox.ini
**Description:** Added python 3.8 in test matrix
**JIRA:** https://openedx.atlassian.net/browse/BOM-1546
=> BOM-1546: Added python 3.8 in test matrix

edx_when/models.py, pylintrc, pylintrc_tweaks, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.in, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, tox.ini
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1656
=> BOM-1656: Removed caniusepython3

edx_when/__init__.py, edx_when/api.py, env/pyvenv.cfg, tests/test_api.py, tests/test_models_app/migrations/0001_initial.py, tests/test_models_app/models.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Fixes get_schedules_by_due_date to include abs_dates

env/pyvenv.cfg
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Removes an accidental pyenv.cfg

edx_when/__init__.py, edx_when/api.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> Use map_into_course to change course_key in UsageKeys

docs/conf.py, edx_when/field_data.py, tests/test_api.py
**Issue:** [BOM-1828](https://openedx.atlassian.net/browse/BOM-1828)
- Remove usages of package `six`.
=> Remove usage of package six

.github/workflows/upgrade-python-requirements.yml, tox.ini
JIRA: https://openedx.atlassian.net/browse/BOM-2601
=> feat: Added upgrade-python-requirements workflow

setup.py
These are now warnings in newer pylints.
=> fix: avoid some pylint errors in setup.py

Makefile, requirements/constraints.txt
=> build: Add in Common Constraints requirements file

Makefile
=> Revert: "build: Add updating pylintrc to upgrade command"

requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
=> chore: update pip-tools & requirements

.github/workflows/upgrade-python-requirements.yml
Updates python requirements upgrade schedule to match other Cosmonauts owned repositories.
=> fix: update python requirements upgrade schedule

requirements/base.txt, requirements/ci.in, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt, tox.ini
Issue: https://github.com/edx/edx-arch-experiments/issues/130
=> fix: Replaced whitelist_externals with allowlist_externals in tox and removed tox-battery

.github/workflows/ci.yml, CHANGELOG.rst, edx_when/__init__.py, edx_when/models.py, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, setup.py, tests/test_xblock_services.py, tox.ini
Related to https://github.com/openedx/axim-engineering/issues/1045
=> Add support for python 3.11

edx_when/migrations/0005_auto_20190911_1056.py
…ysql.
**Description:** I am working on adding postgresql support to edx-platform, in order to support the implementation it is first step to fix the migrations to allow creating database structure on postgres and mysql as well.
=> fix: Update the migration to make it compatible with postgresql and mysql

.github/workflows/pypi-publish.yml
Publish using a newer version of Python.
=> build: Update pypi-publish.yml
